---
# import tasks file to initiate the patching
- name: Defining patching Type
  debug:
    msg: "Patching_type: {{ Patching_type }}"


- name: creating report with package list
  import_tasks: report.yml
  when: Patching_type == "report"


- name: creating report with package list
  import_tasks: update.yml
  when: Patching_type == "update"


- name: creating report with package list
  import_tasks: rollback.yml
  when: Patching_type == "rollback"
