- name: "creating report time"
  set_fact:
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
  delegate_to: localhost
  run_once: true

- name: "Check the Redhat subscription status is valid"
  shell:  subscription-manager status |  grep "Status:" | awk '{print $NF}'
  changed_when: false
  when: ansible_distribution == "RedHat"
  register: subscription_status

- name: "Please check the RH subscription first"
  shell: 
  when: ansible_distribution == "RedHat" and subscription_status.stdout != "Current"

- name: creating dupilicate yum list for the host
  ansible.builtin.shell: yum list updates | awk '/Updated Packages/{p=1}p' >/tmp/yum_updates_{{ timestamp }}

- name: copying yum update file to local ansible host
  ansible.builtin.fetch:
    src: /tmp/yum_updates_{{ timestamp }}
    dest: /tmp/{{ inventory_hostname }}
    flat: yes